remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /assets/img/My Portrait.jpg
description: >-
  ğŸ“ Based in Los Angeles, CA <br>
  ğŸ“ Contact me 714-858-7494 <br>
  ğŸ“§ kdpham@umass.edu (School) <br>
  ğŸ’Œ kdpham1002@gmail.com (Personal) <br>
  <br>
  ğŸ“ I'm a Master's student majoring in Business Analytics and Data Science. <br>
  ğŸ“Š I'm passionate about using data to uncover insights and support strategic decision-making. <br>
  ğŸ“ˆ My experience in finance and healthcare has enabled me to strengthen my data analysis and research skills. <br>
  ğŸ§‘â€ğŸ’» Proficient in Python, SQL, and Tableau; <br> while actively enhancing my expertise in Data Engineering and Cloud technologies. <br>

# show_downloads: true
theme: jekyll-theme-minimal