remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /assets/img/My Portrait.jpg
description:
  - ğŸ“ Based in Los Angeles, CA
  - ğŸ“ Contact me 714-858-7494
  - ğŸ“§ kdpham@umass.edu (School)
  - ğŸ’Œ kdpham1002@gmail.com (Personal)
  -
  - ğŸ“ I'm a Master's student majoring in Business Analytics and Data Science.
  - ğŸ“Š I'm passionate about using data to uncover insights and support strategic decision-making.
  - ğŸ“ˆ My experience in finance and healthcare has enabled me to strengthen my data analysis and research skills.
  - ğŸ§‘â€ğŸ’» Proficient in Python, SQL, R, and Tableau; while actively enhancing my expertise in Data Engineering and Cloud technologies.
  # - ğŸ§‘â€ğŸ’» Proficient in Python, SQL, R, Tableau, and currently advancing my skills in Data Engineering and Cloud technologies.

# show_downloads: true
theme: jekyll-theme-minimal